### PR TITLE
Answered Bio section of assignment 1

### PR DESCRIPTION
**Pull request by jacobgould**
I have updated the bio section of the assignment, and I'm following on online tutorial to submit the first section of the assignment.  Hope that's ok, I read in the discussion board this is possible.  Jake

### CODE REVIEW

**Comment by jacobgould** [comment]
Adding in my first attempt at homework for R

**Comment by jacobgould** [comment]
adding Python assignment as well

**Comment by brisbia** [comment]
Nice job on the R assignment!  On problem 1.7, can you think of a shorter piece of code that would do the same thing?
Yes, it's a good idea to sync your changes to GitHub as you go, so that you can back up to a previous version in case you accidentally create a major bug.

**Comment by mandariehl** [comment]
The python and biography portions look great. Keep up the good work!

**Pull request closed without merging**
