### PR TITLE
Homework 1 Complete

### PR DESCRIPTION
**Pull request by cjenn214**

### CODE REVIEW

**Comment by brisbia** [comment]
Nice job on the R assignment!  Please include your output, not just the code.  Your answer to problem 1.7 is answering a slightly different question than what we asked.

**Comment by mandariehl** [comment]
The python and biography portions look great. Keep up the good work!

**Comment by cjenn214** [comment]
Excellent, that sounds good.  I will include the output going forward!

Thanks!

**Comment by cjenn214** [comment]
Hi!

Just a heads up, I answered the Python assignment question 2a in the 1b
section and the 2b answer in the 2a section.

Sorry for the confusion!

Thanks,

Clint J.

**Comment by cjenn214** [comment]
Hi again,

I am so sorry, I am still getting used to the course calendar and
completely missed the quiz.  Would there be any chance I could take it
today?  I know the deadline information is clearly listed in the syllabus,
so I understand if I am out of luck.

Thanks!

Clint J.

**Comment by mandariehl** [comment]
The quiz is now due at midnight tonight.


________________________________

**Pull request closed without merging**
