### PR TITLE
Completed Assignment 1 Files

### PR DESCRIPTION
**Pull request by rlinsk**

### CODE REVIEW

**Comment by mandariehl** [comment]
The python and biography portions look great. Keep up the good work!

What were the stakes of the bet with your wife?

**Comment by rlinsk** [comment]
Mostly just pride :)

**Comment by rlinsk** [comment]
Regarding the R portion, is there a preferred format for the assignments...  I just used word (.docx) since I could create it directly w/ knitr...

**Comment by brisbia** [comment]
Nice job on the R assignment!  Either .docx or .pdf are good choices for the R assignments, because they'll be convenient for displaying graphs on future assignments.

**Pull request closed without merging**
