### PR TITLE
Master - Ben Sc

### PR DESCRIPTION
**Pull request by schmib83**

### CODE REVIEW

**Comment by brisbia** [comment]
Nice job on the R assignment!  For problem 1.8, what does the sd() function do?

**Comment by mandariehl** [comment]
The python and biography portions look great. Keep up the good work!

**Comment by schmib83** [comment]
I can't view any repositories now using my gethub account schmib83!!! Do
you know why this is?

**Comment by mandariehl** [comment]
I think you must have accidentally left the org, because I see your pull request from assignment 1 as schmib83, but you are no longer a member. I re-invited you.

________________________________

**Comment by schmib83** [comment]
Thank you!!! I've been trying to figure that out for a few days now.  How
did that happen?

**Comment by mandariehl** [comment]
If you didn't click "Leave", then I don't know how it happened. But I see you're back in now, and if it happens again we can investigate further.


________________________________

**Pull request closed without merging**
